<?php
/**
 * Plugin Name: Magic Convert
 * Plugin URI: https://github.com/mboisvertdupras/magic-convert
 * Description: Parallelized, multi-format image conversion for WordPress — serve autogenerated WebP and AVIF images to browsers that support them, with fast, concurrency-safe bulk conversion of large media libraries. A fork of WebP Express.
 * Version: 0.26.2
 * Requires at least: 5.9
 * Requires PHP: 8.1
 * Author: Marc Boisvert-Dupras
 * Author URI: https://github.com/mboisvertdupras
 * License: GPL2
 * Text Domain: magic-convert
 * Network: true
 *
 * Originally based on WebP Express by Bjørn Rosell (https://github.com/rosell-dk/webp-express).
 */

if (!defined('ABSPATH')) exit;

if (PHP_VERSION_ID < 80100) {
    if (!function_exists('magic_convert_php_version_notice')) {
        function magic_convert_php_version_notice() {
            echo '<div class="notice notice-error"><p><strong>Magic Convert</strong> requires PHP 8.1 or higher. ';
            echo 'You are running PHP ' . esc_html(PHP_VERSION) . '. ';
            echo 'The plugin has been deactivated-in-effect (not loaded) to avoid errors. ';
            echo 'Please ask your host to upgrade PHP, then the plugin will load automatically.</p></div>';
        }
    }
    add_action('admin_notices', 'magic_convert_php_version_notice');
    add_action('network_admin_notices', 'magic_convert_php_version_notice');
    return;
}

if (defined('MAGIC_CONVERT_PLUGIN')) exit;

define('MAGIC_CONVERT_PLUGIN', __FILE__);
define('MAGIC_CONVERT_PLUGIN_DIR', __DIR__);

spl_autoload_register('magic_convert_autoload');
function magic_convert_autoload($class) {
    $prefix = 'MagicConvert\\';
    if (strpos($class, $prefix) === 0) {
        $relative = str_replace('\\', '/', substr($class, strlen($prefix)));
        require_once MAGIC_CONVERT_PLUGIN_DIR . '/lib/classes/' . $relative . '.php';
    }
}

if (is_admin()) {
    \MagicConvert\AdminInit::init();
}

add_action('rest_api_init', array('\MagicConvert\RestApi', 'registerRoutes'));

if ( class_exists( 'WP_CLI' ) ) {
    \WP_CLI::add_command('magic-convert', '\MagicConvert\CLI');
}

function magic_convert_process_post() {
    $requestUri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';
    $requestUriNoQS = parse_url($requestUri, PHP_URL_PATH);

    if (!is_string($requestUriNoQS)) {
        $requestUriNoQS = '';
    }

    if (preg_match('/magic-convert-web-service$/', $requestUriNoQS)) {
        include __DIR__ . '/web-service/wpc.php';
        die();
    }
}
add_action( 'init', 'magic_convert_process_post' );

if (\MagicConvert\Option::getOption('magic-convert-alter-html', false)) {
    require_once __DIR__ . '/lib/classes/AlterHtmlInit.php';
    \MagicConvert\AlterHtmlInit::setHooks();
}

add_filter('wp_handle_upload', array('\MagicConvert\HandleUploadHooks', 'handleUpload'), 10, 2);
add_filter('image_make_intermediate_size', array('\MagicConvert\HandleUploadHooks', 'handleMakeIntermediateSize'), 10, 1);
add_filter('wp_delete_file', array('\MagicConvert\HandleDeleteFileHook', 'deleteAssociatedWebP'), 10, 2);

add_action('magic_convert_task_bulk_update_dummy_files', array('\MagicConvert\BiggerThanSourceDummyFilesBulk', 'updateStatus'), 10, 0);
add_action('magic_convert_task_regenerate_config', array('\MagicConvert\Config', 'regenerateConfig'), 10, 0);
add_action('magic_convert_task_regenerate_config_and_htaccess', array('\MagicConvert\Config', 'regenerateConfigAndHtaccessFiles'), 10, 0);
