<?php

namespace MagicConvert;

/**
 * Stable, deterministic partitioning of a bulk-conversion file list into N
 * disjoint shards — the mechanism behind WP-CLI's parallel-by-default bulk
 * conversion (Phase 1.3).
 *
 * ## The problem it solves
 *
 * To parallelize a bulk run, the parent WP-CLI process spawns N children of
 * itself, each told "you handle shard i of n". Every process independently
 * builds the SAME file list (one cheap directory walk per process) and then
 * keeps only the files that belong to its shard. For this to produce a correct,
 * non-overlapping, complete cover, two properties are required:
 *
 *   1. **Determinism** — given the same path, shard index and shard count, the
 *      answer must never change. crc32() is a fixed, content-only checksum (no
 *      seed, no locale, no PHP-version drift), so `crc32($p) % $n` is identical
 *      in the parent and in every child, on every machine. We deliberately do
 *      NOT use PHP's hash randomization-affected functions (array order,
 *      spl_object_hash, etc.).
 *
 *   2. **A canonical key** — the parent and the children must feed the EXACT
 *      same string into crc32(). That string is the *root-relative path* of the
 *      image (e.g. "2021/05/photo.jpg" within the uploads root), NOT an absolute
 *      path. Absolute paths would still partition correctly within a single run,
 *      but the root-relative form is the natural identity that BulkConvert
 *      already produces (see BulkConvert::getListRecursively, which yields paths
 *      with the leading "./" stripped) and keeps shard membership stable even if
 *      the site is moved on disk. Callers MUST pass the root-relative path.
 *
 * Because membership is a pure function of the path, the shards are disjoint by
 * construction: a given path maps to exactly one residue class and therefore
 * exactly one shard. The Phase 1.1 per-file locks remain as a second line of
 * defense (and make even accidentally-overlapping ad-hoc runs safe), but with
 * sharding no two children ever target the same file.
 *
 * This class is intentionally WordPress-independent and side-effect-free.
 */
class ShardFilter
{
    /**
     * Upper bound on the number of shards.
     *
     * One WP bootstrap per child is the dominant cost (per-image process
     * spawning was measured ~178% slower than sequential), so shards are always
     * coarse — a handful, not hundreds. 64 is a generous ceiling that no real
     * deployment approaches; it mainly exists to reject obviously-bogus specs.
     */
    const MAX_SHARDS = 64;

    /**
     * Does the given root-relative path belong to shard $shard of $totalShards?
     *
     * Shards are 1-indexed (shard 1 .. shard $totalShards) to match the
     * human-facing "i/n" spec, while the modulo residue is 0-indexed; hence the
     * "$shard - 1" on the right-hand side.
     *
     * The membership test is `crc32($relativePath) % $totalShards === $shard - 1`.
     * crc32() returns an int that may be negative on 32-bit PHP; PHP's `%`
     * preserves the sign of the dividend, which would break the partition. We
     * normalize with an explicit non-negative modulo so 32-bit and 64-bit hosts
     * agree.
     *
     * @param  string $relativePath   The image's ROOT-RELATIVE path (see class
     *                                 docblock). Passing an absolute path will
     *                                 still partition consistently *within* a run
     *                                 but is not the documented contract.
     * @param  int    $shard           1-based shard index (1 <= $shard <= $totalShards).
     * @param  int    $totalShards     Total number of shards (>= 1).
     * @return bool
     */
    public static function belongs($relativePath, $shard, $totalShards)
    {
        $totalShards = (int) $totalShards;
        $shard = (int) $shard;

        if ($totalShards < 1) {
            // A single (degenerate) shard owns everything; defensive, callers
            // are expected to validate via parseSpec() first.
            return true;
        }

        // Non-negative modulo: crc32() can be negative on 32-bit PHP, and
        // PHP's % keeps the dividend's sign. ((a % n) + n) % n is always in
        // [0, n) regardless of platform word size.
        $residue = ((crc32((string) $relativePath) % $totalShards) + $totalShards) % $totalShards;

        return $residue === ($shard - 1);
    }

    /**
     * Parse and validate a "i/n" shard spec (the value of the internal
     * --shard=<i>/<n> flag).
     *
     * Accepts strictly "<int>/<int>" with:
     *   - 1 <= i <= n          (i is a valid 1-based index into n shards)
     *   - 1 <= n <= MAX_SHARDS  (coarse sharding; reject absurd shard counts)
     *
     * No surrounding whitespace, no leading "+", no extra parts — the spec is
     * machine-generated by the parent process, so we are strict and reject
     * anything malformed rather than guessing.
     *
     * @param  string $spec  e.g. "3/8".
     * @return array{0:int,1:int}  [$i, $n].
     * @throws \InvalidArgumentException  on any malformed / out-of-range spec.
     */
    public static function parseSpec($spec)
    {
        if (!is_string($spec) || !preg_match('/^([0-9]+)\/([0-9]+)$/', $spec, $m)) {
            throw new \InvalidArgumentException(
                'Invalid shard spec "' . (is_string($spec) ? $spec : gettype($spec)) .
                '". Expected the form "i/n", e.g. "3/8".'
            );
        }

        $i = (int) $m[1];
        $n = (int) $m[2];

        if ($n < 1 || $n > self::MAX_SHARDS) {
            throw new \InvalidArgumentException(
                'Invalid shard spec "' . $spec . '": total shards must be between 1 and ' .
                self::MAX_SHARDS . '.'
            );
        }
        if ($i < 1 || $i > $n) {
            throw new \InvalidArgumentException(
                'Invalid shard spec "' . $spec . '": shard index must be between 1 and ' . $n . '.'
            );
        }

        return [$i, $n];
    }
}
